version: "3"
services:
  nginx:
    restart: ${RESTART}
    build: ./nginx
    ports:
      - ${NGINX_EXTERNAL_PORT}:80
    volumes:
      - ${BACKEND_SRC}:${BACKEND_SRC_CONTAINER}
      - ${NGINX_CONFIG}:${NGINX_CONFIG_CONTAINER}
    working_dir: ${RELEASE_BACKEND_SRC_CONTAINER}
    links:
      - php

  php:
    restart: ${RESTART}
    build: ./php-fpm
    volumes:
      - ${BACKEND_SRC}:${BACKEND_SRC_CONTAINER}
    working_dir: ${RELEASE_BACKEND_SRC_CONTAINER}
    depends_on:
      - db

  db:
    restart: ${RESTART}
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_DB_PASS}
      - MYSQL_DATABASE=game
    volumes:
      - ${MYSQL_DB_PATH}:${MYSQL_DB_PATH_CONTAINER}