version: "3"
services:
  nginx:
    restart: ${RESTART}
    build: ./nginx
    ports:
      - ${NGINX_EXTERNAL_PORT}:80
    volumes:
      - ${BACKEND_SRC}:${BACKEND_SRC_CONTAINER}
      - ${NGINX_CONFIG}:${NGINX_CONFIG_CONTAINER}
    working_dir: ${RELEASE_BACKEND_SRC_CONTAINER}

  php:
    restart: ${RESTART}
    build: ./php-fpm
    volumes:
      - ${BACKEND_SRC}:${BACKEND_SRC_CONTAINER}
    working_dir: ${RELEASE_BACKEND_SRC_CONTAINER}
    depends_on:
      - db
    links:
     - db
    extra_hosts:
     - "host.docker.internal:host-gateway"


  db:
    restart: ${RESTART}
    image: mysql:latest
    ports:
      - "3301:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_DB_PASS}
      - MYSQL_DATABASE=game
      - MYSQL_USER=game
      - MYSQL_PASSWORD=123
    volumes:
      - ${MYSQL_DB_PATH}:${MYSQL_DB_PATH_CONTAINER}
